# Esercizio: variante dell’altezza dei presidenti US

Usiamo il dataset president_heights.csv

In [4]:
import numpy as np 
import pandas as pd

data = pd.read_csv("../data/president_heights.csv")
data.head(10)

order                    name  height(cm)
0      1       George Washington         189
1      2              John Adams         170
2      3        Thomas Jefferson         189
3      4           James Madison         163
4      5            James Monroe         183
5      6       John Quincy Adams         171
6      7          Andrew Jackson         185
7      8        Martin Van Buren         168
8      9  William Henry Harrison         173
9     10              John Tyler         183

In [5]:
data.tail(10)

order               name  height(cm)
32     35    John F. Kennedy         183
33     36  Lyndon B. Johnson         193
34     37      Richard Nixon         182
35     38        Gerald Ford         183
36     39       Jimmy Carter         177
37     40      Ronald Reagan         185
38     41  George H. W. Bush         188
39     42       Bill Clinton         188
40     43     George W. Bush         182
41     44       Barack Obama         185

In [99]:
#prima possibilità per selezionare le ultime dieci righe
data.iloc[32:42]
#seconda possibilità per selezionare le ultime dieci righe
data.iloc[32:]
#terza possibilità per selezionare le ultime dieci righe
data[-10:]

order               name  height(cm)
32     35    John F. Kennedy         183
33     36  Lyndon B. Johnson         193
34     37      Richard Nixon         182
35     38        Gerald Ford         183
36     39       Jimmy Carter         177
37     40      Ronald Reagan         185
38     41  George H. W. Bush         188
39     42       Bill Clinton         188
40     43     George W. Bush         182
41     44       Barack Obama         185

__Punto 1: Estrarre i primi 10 e gli ultimi 10 presidenti e calcolare l’altezza media di ogni sottogruppo__

In [10]:
primi10 = data.iloc[0:10]
ultimi10 = data[-10:]
print("Primi 10 presidenti:\n", primi10, "\n")
print("Ultimi 10 presidenti:\n", ultimi10, "\n")

Primi 10 presidenti:
    order                    name  height(cm)
0      1       George Washington         189
1      2              John Adams         170
2      3        Thomas Jefferson         189
3      4           James Madison         163
4      5            James Monroe         183
5      6       John Quincy Adams         171
6      7          Andrew Jackson         185
7      8        Martin Van Buren         168
8      9  William Henry Harrison         173
9     10              John Tyler         183 

Ultimi 10 presidenti:
     order               name  height(cm)
32     35    John F. Kennedy         183
33     36  Lyndon B. Johnson         193
34     37      Richard Nixon         182
35     38        Gerald Ford         183
36     39       Jimmy Carter         177
37     40      Ronald Reagan         185
38     41  George H. W. Bush         188
39     42       Bill Clinton         188
40     43     George W. Bush         182
41     44       Barack Obama         185 



In [14]:
#Media altezza primi 10 presidenti
primi10['height(cm)'].mean()

177.4

In [15]:
#Media altezza ultimi 10 presidenti
ultimi10['height(cm)'].mean()

184.6

__Punto2: Estrarre i presidenti di altezza compresa tra 170 e 180 cm.__

In [44]:
#versione senza operatore logico
presidenti170180 = data.loc[data['height(cm)'] >= 170]
presidenti170180 = presidenti170180.loc[presidenti170180['height(cm)'] <= 180]
presidenti170180

order                    name  height(cm)
1       2              John Adams         170
5       6       John Quincy Adams         171
8       9  William Henry Harrison         173
10     11           James K. Polk         173
11     12          Zachary Taylor         173
12     13        Millard Fillmore         175
13     14         Franklin Pierce         178
16     17          Andrew Johnson         178
17     18        Ulysses S. Grant         173
18     19     Rutherford B. Hayes         174
22     25        William McKinley         170
23     26      Theodore Roosevelt         178
25     28          Woodrow Wilson         180
27     30         Calvin Coolidge         178
30     33         Harry S. Truman         175
31     34    Dwight D. Eisenhower         179
36     39            Jimmy Carter         177

In [55]:
#versione con operatore logico
data.loc[(data['height(cm)'] >= 170) & (data['height(cm)'] <= 180)]

order                    name  height(cm)
1       2              John Adams         170
5       6       John Quincy Adams         171
8       9  William Henry Harrison         173
10     11           James K. Polk         173
11     12          Zachary Taylor         173
12     13        Millard Fillmore         175
13     14         Franklin Pierce         178
16     17          Andrew Johnson         178
17     18        Ulysses S. Grant         173
18     19     Rutherford B. Hayes         174
22     25        William McKinley         170
23     26      Theodore Roosevelt         178
25     28          Woodrow Wilson         180
27     30         Calvin Coolidge         178
30     33         Harry S. Truman         175
31     34    Dwight D. Eisenhower         179
36     39            Jimmy Carter         177

__Punto3: Estrarre i presidenti che si chiamano George e sono più alti di 185 cm.__

In [100]:
data.loc[(data['height(cm)'] >= 185) & (data['name'] == 'George')]
#perché?

Empty DataFrame
Columns: [order, name, height(cm)]
Index: []

In [63]:
#capiamo meglio il funzionamento
#cosa restituisce la condizione logica?
data['height(cm)'] >= 185

0      True
1     False
2      True
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29     True
30    False
31    False
32    False
33     True
34    False
35    False
36    False
37     True
38     True
39     True
40    False
41     True
Name: height(cm), dtype: bool

In [64]:
type(data['height(cm)'] >= 185)

pandas.core.series.Series

La condizione logica restituisce una __serie__ di valori booleani

In [61]:
#ora usiamo la funzione loc()
data.loc[data['height(cm)'] >= 185]

order                   name  height(cm)
0       1      George Washington         189
2       3       Thomas Jefferson         189
6       7         Andrew Jackson         185
15     16        Abraham Lincoln         193
29     32  Franklin D. Roosevelt         188
33     36      Lyndon B. Johnson         193
37     40          Ronald Reagan         185
38     41      George H. W. Bush         188
39     42           Bill Clinton         188
41     44           Barack Obama         185

Quindi, la funzione __loc()__ applicata al __dataset data__ con la __serie di valori booleani come parametro__, produce il __subset di elementi di data corrispondenti a True__

In [65]:
#ora proviamo la seconda condizione
data['name'] == 'George'

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
Name: name, dtype: bool

Nessun valore è True

In [101]:
#proviamo con str.contains()
data['name'].str.contains('George')

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38     True
39    False
40     True
41    False
Name: name, dtype: bool

Ora li abbiamo trovati. Quindi, l'operatore booleano == (così come gli altri <,>, <=,>=) non opera su stringhe. Servono funzioni specifiche per cercare i match su stringhe alfanumeriche (match, contains, etc.)

In [67]:
#ora proviamo la combinazione delle due condizioni logiche
(data['height(cm)'] >= 185) & data['name'].str.match('George')

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38     True
39    False
40    False
41    False
dtype: bool

I valori booleani sono corretti

In [70]:
data.loc[(data['height(cm)'] >= 185) & data['name'].str.match('George')]

order               name  height(cm)
0       1  George Washington         189
38     41  George H. W. Bush         188

__Punto 4: Estrarre i presidenti che si chiamano, come nome di battesimo, George, John, Arthur oppure James__

In [104]:
#data
data.loc[data['name'].str.endswith('Arthur')]

order               name  height(cm)
20     21  Chester A. Arthur         183

In [105]:
#con str.contains() o str.endswith() viene riconosciuto anche Arthur 
#(dettagli u espressioni regolari qui non li vediamo)
data.loc[data['name'].str.match('George') | 
         data['name'].str.match('John') | 
         data['name'].str.match('James') |
         data['name'].str.endswith('Arthur')]

order               name  height(cm)
0       1  George Washington         189
1       2         John Adams         170
3       4      James Madison         163
4       5       James Monroe         183
5       6  John Quincy Adams         171
9      10         John Tyler         183
10     11      James K. Polk         173
14     15     James Buchanan         183
19     20  James A. Garfield         183
20     21  Chester A. Arthur         183
32     35    John F. Kennedy         183
38     41  George H. W. Bush         188
40     43     George W. Bush         182

In [93]:
#senza Arthur come cognome
data.loc[data['name'].str.match('George') | 
         data['name'].str.match('John') | 
         data['name'].str.match('James') |
         data['name'].str.startswith('Arthur')]

order               name  height(cm)
0       1  George Washington         189
1       2         John Adams         170
3       4      James Madison         163
4       5       James Monroe         183
5       6  John Quincy Adams         171
9      10         John Tyler         183
10     11      James K. Polk         173
14     15     James Buchanan         183
19     20  James A. Garfield         183
32     35    John F. Kennedy         183
38     41  George H. W. Bush         188
40     43     George W. Bush         182

In [107]:
#senza Arthur come cognome
data.loc[data['name'].str.match('George') | 
         data['name'].str.match('John') | 
         data['name'].str.match('James') |
         data['name'].str.contains('Arthur')]

order               name  height(cm)
0       1  George Washington         189
1       2         John Adams         170
3       4      James Madison         163
4       5       James Monroe         183
5       6  John Quincy Adams         171
9      10         John Tyler         183
10     11      James K. Polk         173
14     15     James Buchanan         183
19     20  James A. Garfield         183
20     21  Chester A. Arthur         183
32     35    John F. Kennedy         183
38     41  George H. W. Bush         188
40     43     George W. Bush         182